(cl:in-package fsd_common_msgs-msg)
(cl:export '(LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          NORTH_VELOCITY-VAL
          NORTH_VELOCITY
          EAST_VELOCITY-VAL
          EAST_VELOCITY
          GROUND_VELOCITY-VAL
          GROUND_VELOCITY
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          AZIMUTH-VAL
          AZIMUTH
          X_ANGULAR_VELOCITY-VAL
          X_ANGULAR_VELOCITY
          Y_ANGULAR_VELOCITY-VAL
          Y_ANGULAR_VELOCITY
          Z_ANGULAR_VELOCITY-VAL
          Z_ANGULAR_VELOCITY
          X_ACC-VAL
          X_ACC
          Y_ACC-VAL
          Y_ACC
          Z_ACC-VAL
          Z_ACC
          LATITUDE_STD-VAL
          LATITUDE_STD
          LONGITUDE_STD-VAL
          LONGITUDE_STD
          ALTITUDE_STD-VAL
          ALTITUDE_STD
          NORTH_VELOCITY_STD-VAL
          NORTH_VELOCITY_STD
          EAST_VELOCITY_STD-VAL
          EAST_VELOCITY_STD
          GROUND_VELOCITY_STD-VAL
          GROUND_VELOCITY_STD
          ROLL_STD-VAL
          ROLL_STD
          PITCH_STD-VAL
          PITCH_STD
          AZIMUTH_STD-VAL
          AZIMUTH_STD
          INS_STATUS-VAL
          INS_STATUS
          POSITION_TYPE-VAL
          POSITION_TYPE
          SEC_OF_WEEK-VAL
          SEC_OF_WEEK
          GPS_WEEK_NUMBER-VAL
          GPS_WEEK_NUMBER
          TEMPERATURE-VAL
          TEMPERATURE
          WHEEL_SPEED_STATUS-VAL
          WHEEL_SPEED_STATUS
          HEADING_TYPE-VAL
          HEADING_TYPE
          NUMSV-VAL
          NUMSV
))