// Generated by gencpp from file fsd_common_msgs/Cone.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_CONE_H
#define FSD_COMMON_MSGS_MESSAGE_CONE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <std_msgs/String.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct Cone_
{
  typedef Cone_<ContainerAllocator> Type;

  Cone_()
    : position()
    , color()  {
    }
  Cone_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::std_msgs::String_<ContainerAllocator>  _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::fsd_common_msgs::Cone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::Cone_<ContainerAllocator> const> ConstPtr;

}; // struct Cone_

typedef ::fsd_common_msgs::Cone_<std::allocator<void> > Cone;

typedef boost::shared_ptr< ::fsd_common_msgs::Cone > ConePtr;
typedef boost::shared_ptr< ::fsd_common_msgs::Cone const> ConeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::Cone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::Cone_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::Cone_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::Cone_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::Cone_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::Cone_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::Cone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::Cone_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::Cone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::Cone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::Cone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::Cone_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::Cone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a503fe5c66b468cc3dd8166c52d2bed4";
  }

  static const char* value(const ::fsd_common_msgs::Cone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa503fe5c66b468ccULL;
  static const uint64_t static_value2 = 0x3dd8166c52d2bed4ULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::Cone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/Cone";
  }

  static const char* value(const ::fsd_common_msgs::Cone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::Cone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position  # coordinate of cone in [x, y]                      圆锥的坐标\n"
"std_msgs/String color           # color of cone, 'b' = blue, 'y' = yellow, 'r' = red                     观看到圆锥的坐标\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::fsd_common_msgs::Cone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::Cone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::Cone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::Cone_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_CONE_H
