
float64 latitude	
float64 longitude
float64 altitude

float64 north_velocity	
float64 east_velocity
float64 ground_velocity

float64 roll	
float64 pitch
float64 azimuth

float64 x_angular_velocity	
float64 y_angular_velocity
float64 z_angular_velocity

float64 x_acc	
float64 y_acc
float64 z_acc

float32 latitude_std	
float32 longitude_std
float32 altitude_std

float32 north_velocity_std	
float32 east_velocity_std
float32 ground_velocity_std


float32 roll_std	
float32 pitch_std
float32 azimuth_std 


uint32 ins_status	
uint32 position_type	 

float64 sec_of_week	

float64 gps_week_number		

float32 temperature	

uint32 wheel_speed_status	



uint32 heading_type		
uint32 numsv		



